on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: 'main-repo' # Optional: Specify a path to checkout the main repository
    
    - uses: actions/checkout@v2
      with:
        repository: 'owner/llama.cpp' # Replace 'owner/llama.cpp' with the correct repository path
        path: 'main-repo/llama.cpp' # Adjust the path to match your project structure

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "16.0"

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ make

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build -- -j4

    - name: Test
      run: ./build/YourTestExecutable
